### ISSUE TITLE
repo-name is not appearing in Jira issues body.

### ISSUE THREAD

**Issue by BDMalone** [CxRepositories/cx-flow#67]
When --repo-name is specified as command line parameter, It is not appearing in the Jira issue body.  if --repo-url is specified, it is being included with the label "Repository:", but --repo-name is not included at all.

Note that ideally Namespace, Repo and Branch would appear together in that order.

**Comment by kmcdon83** [comment]
Can you provide a bit more information?  How is it being executed?  Can you give the command you are executing?

**Comment by kmcdon83** [comment]
I have identified the issue.  I will update and provide a new release shortly.

**Comment by kmcdon83** [comment]
New release is published on Checkmarx-TS organization.  Please use this repository in the future:
https://github.com/checkmarx-ts/cx-flow/releases/tag/1.4.2

https://github.com/checkmarx-ts/cx-flow.git
