### ISSUE TITLE
Azure devops: Error 500 when testing the pull request

### ISSUE THREAD

**Issue by fredericmalo** [CxRepositories/cx-flow#68]
Error 500 when testing the pull request. Thanks!

[event-pull-request-test.txt](https://github.com/CxRepositories/cx-flow/files/3426933/event-pull-request-test.txt)
[payload-pull-request-test.txt](https://github.com/CxRepositories/cx-flow/files/3426934/payload-pull-request-test.txt)
[cx-flow.log](https://github.com/CxRepositories/cx-flow/files/3426935/cx-flow.log)

![s](https://user-images.githubusercontent.com/3525134/61796257-52578080-ae25-11e9-9498-5900d4f65f7c.jpg)

**Comment by kmcdon83** [comment]
This is a known issue.  ADO doesn't appear to send a valid (or values that are expected) Pull request during the testing functionality while registering the webhook.

Will investigate the issue.

**Comment by fredericmalo** [comment]
It is probably because of unauthorized access to:

2019-07-25 10:06:47.336 DEBUG 13524 --- [      flow-web3] o.a.http.wire                             [d35A3qU2] : http-outgoing-3 >> "{"url":"https://qw4643xsnbw2v6auw7wlnm4c3uv3wrlzqf5jkj6hrgnwfkqmzrma@fabrikam-fiber-inc.visualstudio.com/DefaultCollection/_git/Fabrikam-Fiber-Git","branch":"refs/heads/master"}"

**Comment by kmcdon83** [comment]
Fix has been applied to checkmarx-ts orginazation:
https://github.com/checkmarx-ts/cx-flow/pull/7/commits/a03c8b84dc00ef1e60ddea04a24c34a53c8c4de3

Release 1.4.2
