### ISSUE TITLE
Vuln counting

### ISSUE THREAD

**Issue by fredericmalo** [CxRepositories/cx-flow#70]
o	An issue on vuln counting: 
	Please have a look at this pull request: 
                                                https://github.com/fredericmalo/CxFlow-GitHub/pull/7 I’ve created a new XSS, so there is two XSS but the details table show only one XSS.  
	This will be the same when push to master: the issue board shows only one XSS: 
https://github.com/fredericmalo/CxFlow-GitHub/issues 
	One possible explanation would be that the two vector attacks have the same source (but not the same sink) Please have a look at the Cx report screenshot attached.

![CxReport for github flow - 2 different XSS with same source](https://user-images.githubusercontent.com/3525134/61796639-15d85480-ae26-11e9-896e-7a070d19c8d1.png)

**Comment by kmcdon83** [comment]
They have the same file and line, and CxFlow works based on the source.  This is working as designed.

**Comment by kmcdon83** [comment]
Applied fix to SDK:
https://github.com/checkmarx-ts/checkmarx-spring-boot-java-sdk/commit/fa38f04fe5111ac3c844739d0578c80dc90e902a

Changes applied to latest release now found in the latest release:
https://github.com/checkmarx-ts/cx-flow/releases

Note that the repository has changed to the checkmarx-ts organization in GitHub.
