### ISSUE TITLE
Azure devops : wrong project name

### ISSUE THREAD

**Issue by fredericmalo** [CxRepositories/cx-flow#71]
Hello, 

Azure devops integration of the repository : https://dev.azure.com/cxrepository/bookstore
has produced a wrong project name on Checkmarx side: it should be cxrepository-bookstore-master but it is not:

![cx](https://user-images.githubusercontent.com/3525134/61856546-a06e9180-aec2-11e9-8c97-36eae4e23d8f.png)

multi-tenant parameter is set to false

Thanks !

**Comment by kmcdon83** [comment]
In Azure DevOps, they have a grouping of repositories under a project.  In your senario it looks like you created a project called bookstore, and then a repo under it called bookstore.  In the event you create a new repo under the bookstore project can you confirm that the project is created as bookstore-<repo>-<branch>?

A project is treated similar to an organization or group (in gitlab) as it is the higher level namespace with a grouping a repositories.  In my experience ADO projects do not contain a 1 to 1 project to repo - it is usually 1 to many.

If this naming doesn't work for you simply override it with the project=<project> on the url parameter.

**Comment by kmcdon83** [comment]
An enhancement we can add to the backlog is to recursively create teams to map to this structure:
organization\project\repo-branch
This would only be applicable to ADO at this point.

**Comment by fredericmalo** [comment]
Hello, yes : it is created as bookstore-repo-branch

Ok, thanks ! I close the ticket
